- src: git+https://github.com/redtree0/ansible-role-k8s.git
  version: master
- src: git+https://github.com/redtree0/ansible-role-k8sHLF.git
  version: master
- src: git+https://github.com/geerlingguy/ansible-role-nfs.git
  version: master
- src: git+https://github.com/geerlingguy/ansible-role-nodejs.git
  version: master
- src: git+https://github.com/geerlingguy/ansible-role-docker.git
  version: master
- src: git+https://github.com/geerlingguy/ansible-role-ruby.git
  version: master
- src: git+https://github.com/geerlingguy/ansible-role-mysql.git
  version: master