---
- hosts: db
  become: yes
  vars:
    mysql_users:
      - name: devel
        host: "%"
        password: devel
        priv: "SystemInfo.*:ALL"
    mysql_databases:
      - name: SystemInfo
  roles:
    - ansible-role-mysql
  tasks:
    - name: 'Import file.sql similar to mysql -u <username> -p <password> < hostname.sql'
      mysql_db:
        state: import
        name: SystemInfo
        target: /home/vagrant/sync_dir/setup.sql